name: Build and Deploy to Docker hub

on:
  push:
    branches:
      -master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2

    - name: log in to docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}  # username we have to create in github repo
        password: ${{ secrets.DOCKER_PASSWORD }}  # password we have to create in github repo

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: 100xDevs/web-app:latest # replace with your docker hub username and repository

    - name: Verify Pushed Image
      run: docker pull 100xDevs/web-app:latest # replace with your docker hub username and repository